version: "3.9"
services:
  ai-counselor:
    build: .
    ports:
      - "5656:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./.flake8:/.flake8
      - ./Makefile:/Makefile
      - ./pyproject.toml:/pyproject.toml
      - ./requirements.lock:/requirements.lock
      - ./requirements-dev.lock:/requirements-dev.lock
      - ./src:/src
      - ./tests:/tests
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
