# fly.toml app configuration file generated for ai-counselor on 2024-01-05T13:42:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-counselor"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
