name: ci

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
  LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
  LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker set up
        run: |
          docker compose up --build -d
      - name: run CI
        run: |
          make ci-container
